//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenBased_Web_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int S_Id { get; set; }
        public string S_Name { get; set; }
        public string S_Address { get; set; }
        public int S_Class { get; set; }
    }
}
